#! /usr/bin/env python
#
# Generated by PAGE version 4.1
# In conjuction with Tcl version 8.6
#    Nov. 28, 2013 06:55:56 PM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *
try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1
from myPackets import MyPacket
import pTables
import boxes

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    root.title('PacketWarrior')
    root.geometry('400x35+319+74')
    root.configure(bg="#F1F1F1")
    set_Tk_var()
    w = PacketWarrior (root)
    init()
    root.mainloop()

w = None
def create_PacketWarrior (root):
    '''Starting point when module is imported by another program.'''
    global w, w_win
    capturing = None
    if w: # So we have only one instance of window.
        return
    w = Toplevel (root)
    w.title('PacketWarrior')
    w.geometry('400x35+319+74')
    root.configure(bg="#F1F1F1")
    set_Tk_var()
    w_win = PacketWarrior (w)
    init()
    return w_win

def destroy_PacketWarrior ():
    global w
    w.destroy()
    w = None


def set_Tk_var():
    # These are Tk variables used passed to Tkinter and must be
    # defined before the widgets using them are created.
    global NewCheck
    NewCheck = StringVar()


def init():
    pass

class PacketWarrior(Frame):
    data = {}
    pList = []
    
    '''
    pkt = MyPacket('5','90','192.168.2.1','255.255.255.255','TCP')
    pList.append(pkt)
    pkt = MyPacket('90','9','255.255.255.255','192.168.2.1','TCP')
    pList.append(pkt)
    pkt= MyPacket('9','91','192.168.2.1','255.255.255.255','TCP')
    pList.append(pkt)
    pkt= MyPacket('91','10','255.255.255.255','192.168.2.1','TCP')
    pList.append(pkt)
    pkt= MyPacket('10','92','192.168.2.1','255.255.255.255','TCP')
    pList.append(pkt)
    '''

    def __init__(self, master=None):
        Frame.__init__(self, master)
        self.grid(ipady=0)
        self.PktList = []

        for r in range(1):
            self.master.rowconfigure(r, weight=1)    
        for c in range(11):
            self.master.columnconfigure(c, weight=0)

        _bgcolor = 'systemWindowBody'  # X11 color: #ffffff
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = 'systemWindowBody' # X11 color: #ffffff
        _ana1color = 'systemWindowBody' # X11 color: #ffffff 
        _ana2color = 'systemWindowBody' # X11 color: #ffffff 
        #self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')

        self.menubar = Menu(master,bg=_bgcolor,fg=_fgcolor)
        master.configure(menu = self.menubar)

        self.packetwarrior = Menu(master,tearoff=0)
        self.menubar.add_cascade(menu=self.packetwarrior,
                activebackground="systemWindowBody",
                activeforeground="#111111",
                background="systemWindowBody",
                foreground="#000000",
                label="PacketWarrior")
        self.packetwarrior.add_command(
                activebackground="systemWindowBody",
                activeforeground="#000000",
                background="systemWindowBody",
                command=self.about,
                foreground="#000000",
                label="About")
        self.packetwarrior.add_command(
                activebackground="systemWindowBody",
                activeforeground="#000000",
                background="systemWindowBody",
                command=self.openHelp,
                foreground="#000000",
                label="Help")
        self.packetwarrior.add_separator(
                background="systemWindowBody")
        self.packetwarrior.add_command(
                activebackground="systemWindowBody",
                activeforeground="#000000",
                background="systemWindowBody",
                command=self.exitPW,
                foreground="#000000",
                label="Exit")
        self.file = Menu(master,tearoff=0)
        self.menubar.add_cascade(menu=self.file,
                activebackground="systemWindowBody",
                activeforeground="#111111",
                background="systemWindowBody",
                foreground="#000000",
                label="File")
        self.file.add_command(
                activebackground="systemWindowBody",
                activeforeground="#000000",
                background="systemWindowBody",
                command=self.openFile,
                foreground="#000000",
                label="Open")
        self.file.add_command(
                activebackground="systemWindowBody",
                activeforeground="#000000",
                background="systemWindowBody",
                command=self.saveFile,
                foreground="#000000",
                label="Save")
        self.file.add_command(
                activebackground="systemWindowBody",
                activeforeground="#000000",
                background="systemWindowBody",
                command=self.saveFileAs,
                foreground="#000000",
                label="Save As...")
        self.file.add_command(
                activebackground="systemWindowBody",
                activeforeground="#000000",
                background="systemWindowBody",
                command=self.closeFile,
                foreground="#000000",
                label="Close")
        self.view = Menu(master,tearoff=0)
        self.menubar.add_cascade(menu=self.view,
                activebackground="systemWindowBody",
                activeforeground="#111111",
                background="systemWindowBody",
                foreground="#000000",
                label="View")
        self.view.add_checkbutton(
                variable=NewCheck,
                activebackground="systemWindowBody",
                activeforeground="#000000",
                background="systemWindowBody",
                command=self.TODO,
                foreground="#000000",
                label="Toolbar")
        self.view.add_checkbutton(
                variable=NewCheck,
                activebackground="systemWindowBody",
                activeforeground="#000000",
                background="systemWindowBody",
                command=self.TODO,
                foreground="#000000",
                label="Packet List")
        self.view.add_checkbutton(
                variable=NewCheck,
                activebackground="systemWindowBody",
                activeforeground="#000000",
                background="systemWindowBody",
                command=self.TODO,
                foreground="#000000",
                label="Packet Details")
        self.capture = Menu(master,tearoff=0)
        self.menubar.add_cascade(menu=self.capture,
                activebackground="systemWindowBody",
                activeforeground="#111111",
                background="systemWindowBody",
                foreground="#000000",
                label="Capture")
        self.capture.add_command(
                activebackground="systemWindowBody",
                activeforeground="#000000",
                background="systemWindowBody",
                command=self.setDevice,
                foreground="#000000",
                label="Set Device")
        self.capture.add_command(
                activebackground="systemWindowBody",
                activeforeground="#000000",
                background="systemWindowBody",
                command=self.setFilters,
                foreground="#000000",
                label="Filters")
        self.capture.add_separator(
                background="systemWindowBody")
        self.capture.add_command(
                activebackground="systemWindowBody",
                activeforeground="#000000",
                background="systemWindowBody",
                command=self.startCapture,
                foreground="#000000",
                label="Start Capture")
        self.capture.add_command(
                activebackground="systemWindowBody",
                activeforeground="#000000",
                background="systemWindowBody",
                command=self.pauseCapture,
                foreground="#000000",
                label="Pause Capture")
        self.capture.add_command(
                activebackground="systemWindowBody",
                activeforeground="#000000",
                background="systemWindowBody",
                command=self.stopCapture,
                foreground="#000000",
                label="stopCapture")
    

        # Toolbar set up

        self._img1 = PhotoImage(file="img/open.gif")
        self.OpenButton = Button(master, image=self._img1, command=self.openFile, border=0)
        self.OpenButton.grid(row=0, column=0)

        self._img2 = PhotoImage(file="img/save.gif")
        self.SaveButton = Button(master, image=self._img2, command=self.saveFile, border=0)
        self.SaveButton.grid(row=0, column=1)

        self._img3 = PhotoImage(file="img/saveAS.gif")
        self.AsButton = Button(master, image=self._img3, command=self.saveFileAs, bd=-2)
        self.AsButton.grid(row=0, column=2)

        self._img4 = PhotoImage(file="img/close.gif")
        self.CloseButton = Button(master, image=self._img4, command=self.closeFile, bd=-2)
        self.CloseButton.grid(row=0, column=3)

        self._img5 = PhotoImage(file="img/filter.gif")
        self.FilterButton = Button(master, image=self._img5, command=self.setFilters, bd=-2)
        self.FilterButton.grid(row=0, column=4)

        self._img6 = PhotoImage(file="img/play.gif")
        self.StartButton = Button(master, image=self._img6, command=self.startCapture, bd=-2)
        self.StartButton.grid(row=0, column=5)

        self._img7 = PhotoImage(file="img/pause.gif")
        self.PauseButton = Button(master, image=self._img7 , command=self.pauseCapture, bd=-2)
        self.PauseButton.grid(row=0, column=6)

        self._img8 = PhotoImage(file="img/stop.gif")
        self.StopButton = Button(master, image=self._img8, command=self.stopCapture, bd=-2)
        self.StopButton.grid(row=0, column=7)

        self._img9 = PhotoImage(file="img/help.gif")
        self.HelpButton = Button(master, image=self._img9, command=self.openHelp, bd=-2)
        self.HelpButton.grid(row=0, column=8)

        self._img10 = PhotoImage(file="img/exit.gif")
        self.ExitButton = Button(master, image=self._img10, command=self.exitPW, bd=-2)
        self.ExitButton.grid(row=0, column=9)

        self.PktLstButton = Button(master, command=self.showPacketList, bd=-2, text="PacketList")
        self.PktLstButton.grid(row=0, column=10)

        # End Toolbar

    def TODO(self):
        print ('TODO')
        sys.stdout.flush()

    def showPacketList(self):
        self.buildList()
        win = pTables.PTable(self.data)

    def about(self):
        import tkMessageBox
        tkMessageBox.showinfo("About PacketWarrior", "The About functionality not yet implemented.")
        sys.stdout.flush()

    def closeFile(self):
        print ('closeFile')
        sys.stdout.flush()

    def exitPW(self):
        sys.exit()

    def openFile(self):
        import tkFileDialog,csv
        input_file = tkFileDialog.askopenfile(parent=root,mode='rb',title='Choose a file')
        if input_file != None:
            reader = csv.reader(input_file,delimiter=',', quotechar='"')
            for row in reader:
                self.data[row[0]]=row[1:]
        input_file.close()
        #print self.data.viewitems()
        print ('openFile')
        sys.stdout.flush()

    def openHelp(self):
        import tkMessageBox
        tkMessageBox.showinfo("Help", "The Help functionality not yet implemented.")
        sys.stdout.flush()

    def pauseCapture(self):
        print ('pauseCapture')
        sys.stdout.flush()

    def saveFile(self):
        import csv
        w = csv.writer(open("output.csv", "w"))
        for key, val in self.data.items():
            w.writerow([key, val])
        print ('saveFile')
        sys.stdout.flush()

    def saveFileAs(self):
        import tkMessageBox
        tkMessageBox.showinfo("Save As", "The Save As functionality not yet implemented.")
        sys.stdout.flush()

    def setDevice(self):
        import tkMessageBox
        tkMessageBox.showinfo("Set Device", "The Set Device functionality not yet implemented.")
        sys.stdout.flush()

    def setFilters(self):
        tframe = Tk()
        tframe.title('Set Filter')
        filterLabel =Label(tframe, text="Select a filter using the up/down arrowhead keys \nor keyboard up/down arrow keys.\n Replace the value in quotes.")
        filterLabel.grid(column=0, row=0)
        self.box_value = StringVar()
        self.box = ttk.Combobox(tframe, textvariable=self.box_value)
        self.box['values'] = ('host \'host\'', 'src host host', 'dst host host', 'gateway host', 'dst net net', 'src net net', 
            'net net', 'dst port port', 'src port port', 'port port', 'ip proto protocol', 'ip6 proto protocol',
            'ip broadcast', 'ip multicast', 'ip6 multicast')
        self.box.current(0)
        self.box.bind('<Return>', self.updateFilter)
        self.box.grid(column=0, row=1)

    def updateFilter(self, crap):
        print self.box_value.get()
        sys.stdout.flush()


    def startCapture(self):
        import tkMessageBox
        tkMessageBox.showinfo("Start Capture", "The Start Capture functionality not yet implemented.")
        sys.stdout.flush()
        #tell PacketEngine to start capture

    def stopCapture(self):
        import tkMessageBox
        tkMessageBox.showinfo("Stop Capture", "The Stop Capture functionality not yet implemented.")
        sys.stdout.flush()
        #self.buildList()
        #tell PacketEngine to stop capture

    def buildList(self):
        if self.pList:
            for i in range(len(self.pList)):
                self.data[i] = self.pList[i].__dict__

if __name__ == '__main__':
    vp_start_gui()




